development:
  adapter: postgresql
  database: contacts_crm_dev
  username: crm_user
  password: 'AlfredWC1E'
  host: localhost
  pool: 5
  timeout: 10

test:
  adapter: postgresql
  database: contacts_crm_test
  username: crm_user
  password: 'AlfredWC1E'
  host: localhost
  pool: 5
  timeout: 10

production:
  adapter: postgresql
  database: contacts_crm_production
  username: crm_user
  password: 'AlfredWC1E'
  host: localhost
  pool: 5
  timeout: 10